---
- name: Deploy OTMS application
  hosts: localhost
  gather_facts: False
  tasks:
    # - name: Ensure Docker is installed
    #   apt:
    #     name: docker.io
    #     state: present
    #   become: true

    # - name: Ensure Docker Compose is installed
    #   get_url:
    #     url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
    #     dest: /usr/local/bin/docker-compose
    #     mode: '0755'
    #   become: true
    #   when: ansible_distribution == "Ubuntu"

    # - name: Apply db config
    #   shell: kubectl apply -f ../k8s-deploy/db-config.yml
      
    - name: Pull frontend from Docker Hub
      shell: docker pull subhodip703/ui-otms:0.0.1

    - name: Pull backend from Docker Hub
      shell: docker pull subhodip703/api-otms:0.0.1

    # - name: Install kubernetes library
    #   pip:
    #     name: kubernetes
    #     state: present
    #     executable: pip3

    - name: Apply Persistent Volume and Claim
      kubernetes.core.k8s:
        kubeconfig: /home/subho/.kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/db-config.yml.j2') }}"
    
    - name: Deploying Database
      kubernetes.core.k8s:
        kubeconfig: /home/subho/.kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/db-deployment-service.yml.j2') }}"
