---
- name: Deploy OTMS application
  hosts: localhost
  gather_facts: False
  tasks:
      
    - name: Pull frontend from Docker Hub
      shell: docker pull rishavchandel/ui-otms:0.0.1

    - name: Pull backend from Docker Hub
      shell: docker pull rishavchandel/api-otms:0.0.1

    - name: Install kubernetes Python library on remote hosts
      pip:
        name: kubernetes
        state: present
        executable: pip3

    - name: Persistent Volume setup
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/otms-db-pv.yml.j2') }}"

    - name: Persistent Volume Claim setup
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/otms-db-pvc.yml.j2') }}"

    - name: Database Configurations Setup
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/db-config.yml.j2') }}"
    
    - name: Database Deployment
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/db-deployment-service.yml.j2') }}"

    - name: Backend Configurations Setup
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/backend-config.yml.j2') }}"
    
    - name: Backend Deployment
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/backend-deployment-service.yml.j2') }}"
    
    - name: Frontend Deployment
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/frontend-deployment-service.yml.j2') }}"

    - name: Frontend Scaling
      kubernetes.core.k8s:
        kubeconfig: /etc/ansible/kube/config
        state: present
        definition: "{{ lookup('template', '../k8s-deploy/frontend-scaling.yml.j2') }}"
