apiVersion: apps/v1
kind: Deployment
metadata:
  name: otms-backend-deployment
  labels:
    app: otms-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otms-backend
  template:
    metadata:
      labels:
        app: otms-backend
    spec:
      containers:
        - name: otms-backend
          image: otms-all-backend:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: otms-db-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: otms-db-config
                  key: MYSQL_PORT
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: otms-db-config
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: otms-db-config
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: otms-db-config
                  key: MYSQL_DATABASE

---

apiVersion: v1
kind: Service
metadata:
  name: otms-backend-service
spec:
  selector:
    app.kubernetes.io/name: otms-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
