apiVersion: v1
kind: ConfigMap
metadata:
  name: otms-db-config
data:
  MYSQL_HOST: "otms-db-service"
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: "subho123"
  MYSQL_USER: "root"
  MYSQL_DATABASE: "exam-portal"